title: Your Site Title
description: A short description of your site's purpose
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
show_downloads: "false"
# google_analytics: [Your Google Analytics tracking ID]
