title: JVZ stelsel documentatie
description: Deze JZV documentatie site biedt u inzicht, overzicht en duiding in de werking van het stelsel en de gegevensdeling daarbinnen. 
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
show_downloads: "false"
# google_analytics: [Your Google Analytics tracking ID]
